%YAML 1.2
---

root: true

extends: 'eslint:recommended'

globals:
  # From <https://searchfox.org/mozilla-central/rev/c938c7416c633639a5c8ce4412be586eefb48005/modules/libpref/parser/src/lib.rs#296>
  pref: true
  user_pref: true
  sticky: true
  locked: true
  sticky_pref: true

rules:
  # Expect a semicolon after each statement.
  semi:
    - "error"
    - "always"
    -
      omitLastInOneLineBlock: false

  # As internal code style, don't allow tabulation.
  no-tabs: "error"
  # ... nor trailing spaces !
  no-trailing-spaces: "error"

  # Expect only double-quoted strings.
  quotes:
    - "error"
    - "double"

  # Don't allow whitespace before semicolons.
  semi-spacing:
    - "error"
    -
      before: false

  # Don't allow irregular whitespace characters in our sheet.
  no-irregular-whitespace:
    - "error"
    -
      skipStrings: false
      skipComments: false
