---
name: Linting

on: [push, pull_request]

jobs:
  build:
    name: Run ESLint on user.js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5

      - run: npm install eslint @eslint/js
      - run: npx eslint -c .eslint.config.mjs user.js
