---
name: Linting

on: [push, pull_request]

jobs:
  build:
    name: Run ESLint on user.js
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - run: npm install -g eslint
      - run: eslint user.js
