---
name: Linting

on: [push, pull_request]

jobs:
  build:
    name: Run ESLint on user.js
    runs-on: ubuntu-latest
    env:
      ESLINT_USE_FLAT_CONFIG: false

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - run: npm install -g eslint
      - run: eslint user.js
